### ISSUE TITLE
扫码识别不出来

### ISSUE THREAD

**Issue by iPhonePKAndroid** [JoJoWuBeBetter/zhipin-auto#1]
扫码识别不出来

**Comment by JoJoWuBeBetter** [comment]
这个是因为我用IDEA写的时候，白格的字符大小和WIN 系统CMD的字符大小不一样。我修改了一下

**Comment by iPhonePKAndroid** [comment]
不用扫码，直接保存cookie值，自己从浏览器拿

**Comment by clouddemo1** [comment]
> 不用扫码，直接保存cookie值，自己从浏览器拿

请教一下具体怎样操作？我用Chrome 的F12直接复制Cookies，然后放到Cookies =这个等号后面，但是会报错 ConfigParser.InterpolationSyntaxError: '%' must be followed by '%' or '('

加上双引号单引号也都不行，不知道怎么弄。

还有这个脚本是针对招聘者还是求职者用的？上面的作者 @JoJoWuBeBetter 说的“没有企业直聘账号了”是什么意思？这个是给招聘的企业用的吗？
